# Generated by Django 6.0.2 on 2026-02-09 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_added_at_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 9, 16, 11, 42, 774395, tzinfo=datetime.timezone.utc)),
        ),
    ]
